### ISSUE TITLE
Geen fijne variabel naam

### ISSUE THREAD

**Issue by SilvanDomino** [DBeumans/GD2A-EndlessRunner#2]
Je hebt feedback gekregen van **SilvanDomino**
op:

``` c
Rigidbody2D rb2d; 
```

URL: https://github.com/DBeumans/GD2A-EndlessRunner/blob/master/Assets/Scripts/Player/Player_Movement.cs

Feedback: Het is geen fijne leesbare variabele naam. Het is lastig snel lezen wat deze variabele precies is zonder op te zoeken wat voor object het is.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/)

**Comment by DBeumans** [comment]
Hi, SilvanDomino,

We hebben de variable naam aangepast, 

`Rigidbody2D _rigidBody2D;`

Dankjewel voor de feedback!
